# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 228b16362d1e299377f733766e6f4eaf7ab29b8d4c97bb1586823785cc6f9a3a023b88a4f25aa7d6a8981eca312ed09df97b2570dcc40f1d100a72b376903d8c

test:
  secret_key_base: 379ffb62ce0bd80f2a2e888c2b5abd09f6659ad0be4910548be12a2315fe626f69d72baf38320863acb662aee6b25f75d630d2a219e81587300ddd7b239ec759

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
